/* eslint-disable  func-names */
/* eslint quote-props: ["error", "consistent"]*/
module.exports = {
    ACTIONS_EN_GB: {
        'navigate back': 'navigating back',
        'navigate forward': 'navigating forward',
        'go forward': 'navigating back',
        'go back': 'navigating forward',
        'open facebook': 'loading facebook',
        'open youtube' : 'loading youtube',
        'open google': 'loading google',
        'open twitter': 'loading twitter',
        'open hacker news': 'loading hacker news',
        'show news': 'showing recent articles on the guardian',
        'scroll down': 'scrolling down',
        'scroll up': 'scrolling up',
        'press enter': 'enter pressed',
        'press spacebar': 'spacebar pressed',
        'search with google': 'what would you like to search for?',
        'new tab': 'which website shall I load?',
        'close tab': 'tab closed',
        'refresh page': 'page reloaded',
        'refresh': 'page reloaded',
        'reload page': 'page reloaded',
        'show options': 'links highlighted',
        'display options': 'links highlighted',
        'highlight options': 'links highlighted',
        'show links': 'links highlighted',
        'display links': 'links highlighted',
        'highlight links': 'links highlighted',
        'open 1st': 'opening first link',
        'open 2nd': 'opening second link',
        'open 3rd': 'opening third link',
        'open 4th': 'opening fourth link',
        'open first': 'opening first link',
        'open second': 'opening second link',
        'open third': 'opening third link',
        'open fourth': 'opening fourth link',
        'open 1st link': 'opening first link',
        'open 2nd link': 'opening second link',
        'open 3rd link': 'opening third link',
        'open 4th link': 'opening fourth link',
        'open first link': 'opening first link',
        'open second link': 'opening second link',
        'open third link': 'opening third link',
        'open fourth link': 'opening fourth link',
        'search near-by supermarkets': 'Here\'s what I found on google'
    }
};
    